[[session]]
name = "ğŸ“¥ Downloads"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "ğŸ”¨ tmux"
path = "~/dotfiles/tmux/"
startup_command = "nvim .tmux.conf"

[[session]]
name = "ğŸ”¨ dotfiles"
path = "~/dotfiles/"
startup_command = "nvim"

[[session]]
name = "ğŸº Pub"
path = "~/Projects/mine/"
startup_command = "nvim"

[[session]]
name = "ğŸ“ Memo"
path = "~/obsidian/"
startup_command = "nvim"

[[session]]
name = "ğŸ‘” refreshers"
startup_command = "~/.config/sesh/sessions/refreshers.sh"

[[session]]
name = "ğŸš‘ï¸ RPA"
startup_command = "~/.config/sesh/sessions/rpa.sh"
